import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';

const PrivacyPolicyScreen = () => {
  const router = useRouter();

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity 
          onPress={() => router.back()} 
          style={styles.backButton}
        >
          <Ionicons name="arrow-back" size={24} color="#fff" />
          <Text style={styles.backButtonText}>Back</Text>
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Privacy Policy</Text>
        <View style={styles.placeholder} />
      </View>

      <ScrollView style={styles.content}>
        <View style={styles.section}>
          <Text style={styles.lastUpdated}>Last updated: April 01, 2025</Text>
          
          <Text style={styles.paragraph}>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </Text>
          
          <Text style={styles.paragraph}>
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
          </Text>
          
          <Text style={styles.sectionTitle}>Interpretation and Definitions</Text>
          <Text style={styles.subSectionTitle}>Interpretation</Text>
          <Text style={styles.paragraph}>
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </Text>
          
          <Text style={styles.subSectionTitle}>Definitions</Text>
          <Text style={styles.paragraph}>
            For the purposes of this Privacy Policy:
          </Text>
          <View style={styles.bulletPoints}>
            <Text style={styles.bulletPoint}>• Account means a unique account created for You to access our Service or parts of our Service.</Text>
            <Text style={styles.bulletPoint}>• Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</Text>
            <Text style={styles.bulletPoint}>• Application refers to WasteRoute!, the software program provided by the Company.</Text>
            <Text style={styles.bulletPoint}>• Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to WasteRoute!.</Text>
            <Text style={styles.bulletPoint}>• Country refers to: Texas, United States</Text>
            <Text style={styles.bulletPoint}>• Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.</Text>
            <Text style={styles.bulletPoint}>• Personal Data is any information that relates to an identified or identifiable individual.</Text>
            <Text style={styles.bulletPoint}>• Service refers to the Application.</Text>
            <Text style={styles.bulletPoint}>• Service Provider means any natural or legal person who processes the data on behalf of the Company.</Text>
            <Text style={styles.bulletPoint}>• Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</Text>
            <Text style={styles.bulletPoint}>• You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</Text>
          </View>
          
          <Text style={styles.sectionTitle}>Collecting and Using Your Personal Data</Text>
          <Text style={styles.subSectionTitle}>Types of Data Collected</Text>
          <Text style={styles.paragraph}>Personal Data</Text>
          <Text style={styles.paragraph}>
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
          </Text>
          
          <View style={styles.bulletPoints}>
            <Text style={styles.bulletPoint}>• Email address</Text>
            <Text style={styles.bulletPoint}>• First name and last name</Text>
            <Text style={styles.bulletPoint}>• Phone number</Text>
            <Text style={styles.bulletPoint}>• Usage Data</Text>
          </View>
          
          <Text style={styles.paragraph}>Usage Data</Text>
          <Text style={styles.paragraph}>
            Usage Data is collected automatically when using the Service.
          </Text>
          
          <Text style={styles.paragraph}>
            Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </Text>
          
          <Text style={styles.paragraph}>
            When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
          </Text>
          
          <Text style={styles.paragraph}>Information Collected while Using the Application</Text>
          <Text style={styles.paragraph}>
            While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:
          </Text>
          
          <View style={styles.bulletPoints}>
            <Text style={styles.bulletPoint}>• Information regarding your location</Text>
          </View>
          
          <Text style={styles.sectionTitle}>Security of Your Personal Data</Text>
          <Text style={styles.paragraph}>
            The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
          </Text>
          
          <Text style={styles.sectionTitle}>Children's Privacy</Text>
          <Text style={styles.paragraph}>
            Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
          </Text>
          
          <Text style={styles.sectionTitle}>Contact Us</Text>
          <Text style={styles.paragraph}>
            If you have any questions about this Privacy Policy, You can contact us:
          </Text>
          
          <View style={styles.bulletPoints}>
            <Text style={styles.bulletPoint}>• By email: support@wasteroute.app</Text>
          </View>
        </View>
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    paddingTop: 60,
    backgroundColor: '#111',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#fff',
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  backButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '500',
  },
  placeholder: {
    width: 70,
  },
  content: {
    flex: 1,
  },
  section: {
    padding: 20,
  },
  lastUpdated: {
    color: '#6B7280',
    fontSize: 14,
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 12,
    marginTop: 24,
  },
  paragraph: {
    color: '#D1D5DB',
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 16,
  },
  bulletPoints: {
    marginLeft: 8,
    marginBottom: 16,
  },
  bulletPoint: {
    color: '#D1D5DB',
    fontSize: 16,
    lineHeight: 28,
  },
  subSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 8,
    marginTop: 16,
  },
});

export default PrivacyPolicyScreen; 
 
 
 
 
 