create table if not exists geocoded_addresses (
  id bigint generated by default as identity primary key,
  address text not null unique,
  lat numeric not null,
  lng numeric not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_geocoded_addresses_address on geocoded_addresses(address);


